version: '3'
services:
  nginx:
    image: nginx:1.12.2
    ports:
      - "80:80"
    depends_on:
      - tornado
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  tornado:
    build: ./tornado-simple-app
